import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export default function generateComplianceReport(data) {
  const {
    devices = [],
    certificates = [],
    generatedBy = "TrustWipe Enterprise",
  } = data;

  const doc = new jsPDF("p", "mm", "a4");

  const PAGE_WIDTH = doc.internal.pageSize.getWidth();
  const PAGE_HEIGHT = doc.internal.pageSize.getHeight();

  const PRIMARY = [0, 180, 255];
  const DARK = [32, 41, 56];
  const SUCCESS = [22, 163, 74];
  const WARNING = [245, 158, 11];
  const LIGHT = [248, 250, 252];

  //-------------------------------------------------
  // HELPER FUNCTIONS
  //-------------------------------------------------
  function addSectionTitle(text, y) {
    doc.setFontSize(17);
    doc.setFont("helvetica", "bold");
    doc.text(text, 15, y);
    return y + 8;
  }

  function nextY() {
    return doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 42;
  }

  //-------------------------------------------------
  // HEADER
  //-------------------------------------------------
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, PAGE_WIDTH, 28, "F");

  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(23);
  doc.text("TrustWipe Enterprise", 15, 15);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Enterprise Compliance & Audit Report", 15, 22);

  //-------------------------------------------------
  // TITLE
  //-------------------------------------------------
  let y = 42;
  doc.setTextColor(...DARK);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("Compliance Assessment", 15, y);

  y += 10;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated : ${new Date().toLocaleString()}`, 15, y);
  y += 7;
  doc.text(`Generated By : ${generatedBy}`, 15, y);

  //-------------------------------------------------
  // KPI SUMMARY
  //-------------------------------------------------
  const total = devices.length;
  const completed = devices.filter(d => d.status === "Completed").length;
  const pending = devices.filter(d => d.status === "Pending").length;
  const wiping = devices.filter(d => d.status === "Wiping").length;
  const score = total === 0 ? 0 : Math.round((completed / total) * 100);

  y = addSectionTitle("Executive Summary", y + 15);
  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value"]],
    body: [
      ["Total Assets", total],
      ["Completed Sanitizations", completed],
      ["Pending Operations", pending],
      ["Running Operations", wiping],
      ["Certificates Generated", certificates.length],
      ["Compliance Score", `${score}%`],
    ],
    headStyles: { fillColor: PRIMARY },
    theme: "grid",
    alternateRowStyles: { fillColor: LIGHT },
    margin: { top: 40, bottom: 30 },
    pageBreak: "auto",
  });

  //-------------------------------------------------
  // COMPLIANCE TABLE
  //-------------------------------------------------
  y = addSectionTitle("Compliance Standards", nextY());
  autoTable(doc, {
    startY: y,
    head: [["Standard", "Status", "Description"]],
    body: [
      ["NIST SP 800-88 Rev.1", "PASS", "Media Sanitization"],
      ["ISO 27001", "PASS", "Information Security"],
      ["GDPR Article 17", "PASS", "Right to Erasure"],
      ["DoD 5220.22-M", "PASS", "Overwrite Verification"],
      ["HIPAA", "PASS", "Healthcare Compliance"],
    ],
    headStyles: { fillColor: SUCCESS },
    alternateRowStyles: { fillColor: LIGHT },
    theme: "grid",
    margin: { top: 40, bottom: 30 },
    pageBreak: "auto",
  });

  //-------------------------------------------------
  // DEVICE INVENTORY
  //-------------------------------------------------
  y = addSectionTitle("Verified Assets", nextY());
  autoTable(doc, {
    startY: y,
    head: [["Device", "Serial", "Storage", "Capacity", "Status"]],
    body: devices.map(d => [
      d.deviceName,
      d.serialNumber,
      d.storageType,
      d.capacity,
      d.status,
    ]),
    headStyles: { fillColor: PRIMARY },
    alternateRowStyles: { fillColor: LIGHT },
    theme: "striped",
    styles: { fontSize: 10 },
    margin: { top: 40, bottom: 30 },
    pageBreak: "auto",
  });

  //-------------------------------------------------
  // RISK ANALYSIS
  //-------------------------------------------------
  y = addSectionTitle("Risk Assessment", nextY());
  autoTable(doc, {
    startY: y,
    head: [["Risk", "Severity", "Recommendation"]],
    body: [
      [
        "Pending Devices",
        pending ? "Medium" : "None",
        pending ? "Complete sanitization." : "No action required.",
      ],
      [
        "Running Jobs",
        wiping ? "Low" : "None",
        wiping ? "Monitor progress." : "All jobs completed.",
      ],
      [
        "Compliance",
        score === 100 ? "Excellent" : "Review",
        score === 100
          ? "Enterprise fully compliant."
          : "Complete remaining devices.",
      ],
    ],
    headStyles: { fillColor: WARNING },
    alternateRowStyles: { fillColor: LIGHT },
    theme: "grid",
    margin: { top: 40, bottom: 30 },
    pageBreak: "auto",
  });

  //-------------------------------------------------
  // DIGITAL VERIFICATION
  //-------------------------------------------------
  y = addSectionTitle("Digital Verification", nextY());
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("This report has been digitally generated by TrustWipe Enterprise.", 15, y + 10);
  doc.text("Certificate authenticity can be verified through the TrustWipe Verification Portal.", 15, y + 17);
  doc.text("This document is intended for enterprise compliance and audit purposes.", 15, y + 24);

  doc.setDrawColor(...PRIMARY);
  doc.line(15, y + 42, 80, y + 42);
  doc.setFont("helvetica", "bold");
  doc.text("Authorized Digital Signature", 15, y + 50);

  //-------------------------------------------------
  // FOOTER
  //-------------------------------------------------
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setDrawColor(220);
    doc.line(15, PAGE_HEIGHT - 18, PAGE_WIDTH - 15, PAGE_HEIGHT - 18);
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text("TrustWipe Enterprise", 15, PAGE_HEIGHT - 10);
    doc.text("Confidential Compliance Report", PAGE_WIDTH / 2, PAGE_HEIGHT - 10, { align: "center" });
    doc.text(`Page ${i} of ${pages}`, PAGE_WIDTH - 15, PAGE_HEIGHT - 10, { align: "right" });
  }

  return doc;
}
