import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export default function generatePDF(reportData) {
  const {
    devices = [],
    certificates = [],
    wipeJobs = [],
    generatedBy = "TrustWipe Enterprise",
  } = reportData;

  const doc = new jsPDF("p", "mm", "a4");
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const primary = [0, 180, 255];
  const dark = [30, 41, 59];
  const success = [22, 163, 74];

  // Helpers
  function addSectionTitle(title, y) {
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(title, 15, y);
    return y + 8;
  }

  function nextY() {
    return doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 42;
  }

  // Header
  doc.setFillColor(...primary);
  doc.rect(0, 0, pageWidth, 25, "F");
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("TrustWipe Enterprise", 15, 15);
  doc.setFontSize(11);
  doc.text("Secure Data Sanitization & Compliance Platform", 15, 21);

  // Title
  doc.setTextColor(...dark);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("Data Sanitization Report", 15, 42);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated : ${new Date().toLocaleString()}`, 15, 50);
  doc.text(`Generated By : ${generatedBy}`, 15, 57);

  // Executive Summary
  const totalDevices = devices.length;
  const completed = devices.filter(d => d.status === "Completed").length;
  const pending = devices.filter(d => d.status === "Pending").length;
  const wiping = devices.filter(d => d.status === "Wiping").length;
  const completionRate = totalDevices === 0 ? 0 : Math.round((completed / totalDevices) * 100);

  let y = addSectionTitle("Executive Summary", 72);
  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value"]],
    body: [
      ["Total Assets", totalDevices],
      ["Completed Wipes", completed],
      ["Pending Jobs", pending],
      ["Running Jobs", wiping],
      ["Certificates", certificates.length],
      ["Completion Rate", `${completionRate}%`],
    ],
    theme: "grid",
    headStyles: { fillColor: primary },
    margin: { top: 40, bottom: 30 },
    pageBreak: "auto",
  });

  // Compliance
  y = addSectionTitle("Compliance Standards", nextY());
  autoTable(doc, {
    startY: y,
    head: [["Standard", "Status"]],
    body: [
      ["NIST 800-88 Rev.1", "PASS"],
      ["ISO 27001", "PASS"],
      ["GDPR Article 17", "PASS"],
      ["DoD 5220.22-M", "PASS"],
      ["Certificate Verification", "PASS"],
    ],
    headStyles: { fillColor: success },
    theme: "grid",
    margin: { top: 40, bottom: 30 },
    pageBreak: "auto",
  });

  // Device Inventory
  y = addSectionTitle("Device Inventory", nextY());
  autoTable(doc, {
    startY: y,
    head: [["Device", "Serial", "Storage", "Capacity", "Status"]],
    body: devices.map(d => [
      d.deviceName || "-",
      d.serialNumber || "-",
      d.storageType || "-",
      d.capacity || "-",
      d.status || "-",
    ]),
    theme: "striped",
    headStyles: { fillColor: primary },
    styles: { fontSize: 10 },
    margin: { top: 40, bottom: 30 },
    pageBreak: "auto",
  });

  // Wipe Statistics
  y = addSectionTitle("Wipe Statistics", nextY());
  autoTable(doc, {
    startY: y,
    head: [["Statistic", "Value"]],
    body: [
      ["Total Wipe Jobs", wipeJobs.length],
      ["Completed Jobs", completed],
      ["Running Jobs", wiping],
      ["Pending Jobs", pending],
      ["Success Rate", `${completionRate}%`],
    ],
    theme: "grid",
    headStyles: { fillColor: success },
    margin: { top: 40, bottom: 30 },
    pageBreak: "auto",
  });

  // Certificate Summary
  y = addSectionTitle("Certificate Summary", nextY());
  autoTable(doc, {
    startY: y,
    head: [["Certificate", "Device", "Algorithm", "Status"]],
    body: certificates.length
      ? certificates.map(cert => [
          cert.certificateId || cert._id || "-",
          cert.deviceName || cert.deviceId || "-",
          cert.algorithm || "RSA-SHA256",
          cert.status || "Verified",
        ])
      : [["No certificates generated", "", "", ""]],
    theme: "grid",
    headStyles: { fillColor: primary },
    margin: { top: 40, bottom: 30 },
    pageBreak: "auto",
  });

  // Recent Activity
  y = addSectionTitle("Recent Audit Activity", nextY());
  autoTable(doc, {
    startY: y,
    head: [["Date", "Device", "Status", "Remark"]],
    body: devices.slice(0, 10).map(d => [
      new Date().toLocaleDateString(),
      d.deviceName,
      d.status,
      "Audit Logged",
    ]),
    theme: "grid",
    headStyles: { fillColor: success },
    margin: { top: 40, bottom: 30 },
    pageBreak: "auto",
  });

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let page = 1; page <= totalPages; page++) {
    doc.setPage(page);
    doc.setDrawColor(200);
    doc.line(15, pageHeight - 18, pageWidth - 15, pageHeight - 18);
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text("Generated by TrustWipe Enterprise", 15, pageHeight - 10);
    doc.text("Confidential • Secure Data Sanitization Report", pageWidth / 2, pageHeight - 10, { align: "center" });
    doc.text(`Page ${page} of ${totalPages}`, pageWidth - 15, pageHeight - 10, { align: "right" });
  }

  // Digital Verification (precise placement)
  doc.setPage(totalPages);
  let footerY = (doc.lastAutoTable?.finalY || 0) + 25;

  // Estimate block height and available space
  const blockHeight = 25;
  const availableSpace = pageHeight - footerY - 25; // 25mm reserved for footer

  // Add new page only if not enough space
  if (availableSpace < blockHeight) {
    doc.addPage();
    footerY = 40;
  }

  doc.setFontSize(11);
  doc.setTextColor(30);
  doc.setFont("helvetica", "bold");
  doc.text("Digital Verification", 15, footerY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("This report has been digitally generated by the TrustWipe Enterprise Platform.", 15, footerY + 6);
  doc.text("The information contained in this report is intended for compliance and audit purposes.", 15, footerY + 12);
  doc.text("Certificate verification is available through the TrustWipe Verification Center.", 15, footerY + 18);

  return doc;
}
