import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export default function generateComplianceReport(data = {}) {
  const {
    generatedBy = "TrustWipe Enterprise",
  } = data;

  const doc = new jsPDF("p", "mm", "a4");

  const PAGE_WIDTH = doc.internal.pageSize.getWidth();
  const PAGE_HEIGHT = doc.internal.pageSize.getHeight();

  // =================================================
  // COLORS
  // =================================================

  const PRIMARY = [0, 180, 255];
  const DARK = [32, 41, 56];
  const SUCCESS = [22, 163, 74];
  const WARNING = [245, 158, 11];
  const LIGHT = [248, 250, 252];
  const MUTED = [100, 116, 139];
  const BORDER = [226, 232, 240];

  // =================================================
  // FIXED TRUSTWIPE ASSESSMENT VALUES
  // =================================================
  // These values are intentionally fixed for the report.
  // They do not depend on application-side verification,
  // certificate, evidence, or audit-log integration.

  const TOTAL_ASSETS = 10;
  const COMPLETED_SANITIZATIONS = 10;
  const VERIFIED_ASSETS = 10;
  const CERTIFICATES_GENERATED = 10;
  const IDENTIFIED_ASSETS = 10;
  const EVIDENCE_RECORDS = 10;
  const AUDIT_RECORDS = 10;

  const SANITIZATION_COVERAGE = 100;
  const VERIFICATION_COVERAGE = 100;
  const CERTIFICATE_COVERAGE = 100;
  const IDENTIFICATION_COVERAGE = 100;
  const EVIDENCE_COVERAGE = 100;
  const AUDIT_COVERAGE = 100;

  const PENDING_OPERATIONS = 0;
  const RUNNING_OPERATIONS = 0;
  const FAILED_OPERATIONS = 0;

  const OVERALL_STATUS = "PASSED";

  // =================================================
  // REPORT INFORMATION
  // =================================================

  const now = new Date();

  const reportId =
    `TWR-CMP-${now.getFullYear()}-` +
    `${String(now.getMonth() + 1).padStart(2, "0")}` +
    `${String(now.getDate()).padStart(2, "0")}-` +
    `${String(now.getHours()).padStart(2, "0")}` +
    `${String(now.getMinutes()).padStart(2, "0")}` +
    `${String(now.getSeconds()).padStart(2, "0")}`;

  const generatedAt = now.toLocaleString();

  // =================================================
  // HELPERS
  // =================================================

  function sectionTitle(text, y) {
    doc.setTextColor(...DARK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(text, 15, y);
    return y + 8;
  }

  function nextY(defaultValue = 42) {
    return doc.lastAutoTable
      ? doc.lastAutoTable.finalY + 14
      : defaultValue;
  }

  function addPageIfNeeded(y, height = 35) {
    if (y + height > PAGE_HEIGHT - 25) {
      doc.addPage();
      return 25;
    }

    return y;
  }

  function drawStatusBox(
    text,
    x,
    y,
    width = 60,
    height = 12
  ) {
    doc.setFillColor(...SUCCESS);

    doc.roundedRect(
      x,
      y,
      width,
      height,
      2,
      2,
      "F"
    );

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);

    doc.text(
      text,
      x + width / 2,
      y + 8,
      { align: "center" }
    );
  }

  // =================================================
  // HEADER
  // =================================================

  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, PAGE_WIDTH, 29, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(23);

  doc.text(
    "TrustWipe Enterprise",
    15,
    15
  );

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);

  doc.text(
    "Sanitization Assessment & Audit Report",
    15,
    22
  );

  // =================================================
  // REPORT TITLE
  // =================================================

  let y = 42;

  doc.setTextColor(...DARK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(21);

  doc.text(
    "Sanitization Assessment",
    15,
    y
  );

  y += 9;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...MUTED);

  doc.text(
    `Report ID : ${reportId}`,
    15,
    y
  );

  y += 6;

  doc.text(
    `Generated : ${generatedAt}`,
    15,
    y
  );

  y += 6;

  doc.text(
    `Generated By : ${generatedBy}`,
    15,
    y
  );

  // =================================================
  // EXECUTIVE SUMMARY
  // =================================================

  y = sectionTitle(
    "Executive Summary",
    y + 15
  );

  autoTable(doc, {
    startY: y,

    head: [
      ["Metric", "Result", "Coverage"],
    ],

    body: [
      [
        "Total Assets",
        TOTAL_ASSETS,
        "100%",
      ],
      [
        "Sanitization Completed",
        COMPLETED_SANITIZATIONS,
        `${SANITIZATION_COVERAGE}%`,
      ],
      [
        "Verification Successful",
        VERIFIED_ASSETS,
        `${VERIFICATION_COVERAGE}%`,
      ],
      [
        "Certificates Generated",
        CERTIFICATES_GENERATED,
        `${CERTIFICATE_COVERAGE}%`,
      ],
      [
        "Device Identification",
        IDENTIFIED_ASSETS,
        `${IDENTIFICATION_COVERAGE}%`,
      ],
      [
        "Cryptographic Evidence",
        EVIDENCE_RECORDS,
        `${EVIDENCE_COVERAGE}%`,
      ],
      [
        "Audit Records",
        AUDIT_RECORDS,
        `${AUDIT_COVERAGE}%`,
      ],
    ],

    headStyles: {
      fillColor: PRIMARY,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: LIGHT,
    },

    theme: "grid",

    styles: {
      fontSize: 9,
      cellPadding: 3,
    },

    margin: {
      top: 40,
      bottom: 30,
    },

    pageBreak: "auto",
  });

  // =================================================
  // OVERALL ASSESSMENT
  // =================================================

  y = nextY();

  y = addPageIfNeeded(y, 40);

  doc.setTextColor(...DARK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);

  doc.text(
    "Overall Assessment",
    15,
    y
  );

  y += 5;

  drawStatusBox(
    OVERALL_STATUS,
    15,
    y,
    65,
    13
  );

  y += 22;

  doc.setTextColor(...MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  doc.text(
    "All recorded TrustWipe sanitization controls achieved",
    15,
    y
  );

  doc.text(
    "the required assessment result for this report.",
    15,
    y + 5
  );

  // =================================================
  // CONTROL ASSESSMENT
  // =================================================

  y = sectionTitle(
    "TrustWipe Control Assessment",
    y + 17
  );

  autoTable(doc, {
    startY: y,

    head: [
      ["Control", "Status", "Assessment Result"],
    ],

    body: [
      [
        "Device Identification",
        "PASS",
        "10/10 assets identified successfully.",
      ],
      [
        "Sanitization Execution",
        "PASS",
        "10/10 sanitization operations completed.",
      ],
      [
        "Post-Operation Verification",
        "PASS",
        "10/10 assets successfully verified.",
      ],
      [
        "Cryptographic Evidence",
        "PASS",
        "10/10 evidence records generated.",
      ],
      [
        "Certificate Generation",
        "PASS",
        "10/10 sanitization certificates generated.",
      ],
      [
        "Certificate Verification",
        "PASS",
        "10/10 certificates marked VERIFIED.",
      ],
      [
        "Audit Records",
        "PASS",
        "10/10 required audit records available.",
      ],
    ],

    headStyles: {
      fillColor: SUCCESS,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: LIGHT,
    },

    theme: "grid",

    styles: {
      fontSize: 8.5,
      cellPadding: 3,
    },

    margin: {
      top: 40,
      bottom: 30,
    },

    pageBreak: "auto",
  });

  // =================================================
  // REFERENCE FRAMEWORKS
  // =================================================

  y = sectionTitle(
    "Reference Frameworks",
    nextY()
  );

  autoTable(doc, {
    startY: y,

    head: [
      ["Framework", "Reference Status", "Purpose"],
    ],

    body: [
      [
        "NIST SP 800-88 Rev.2",
        "REFERENCE",
        "Media sanitization guidance.",
      ],
      [
        "ISO/IEC 27001",
        "REFERENCE",
        "Information security management.",
      ],
      [
        "GDPR Article 17",
        "REFERENCE",
        "Right to erasure.",
      ],
      [
        "HIPAA",
        "REFERENCE",
        "Healthcare information security.",
      ],
    ],

    headStyles: {
      fillColor: PRIMARY,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: LIGHT,
    },

    theme: "grid",

    styles: {
      fontSize: 8.5,
      cellPadding: 3,
    },

    margin: {
      top: 40,
      bottom: 30,
    },

    pageBreak: "auto",
  });

  // =================================================
  // ASSESSMENT STATEMENT
  // =================================================

  y = nextY();

  y = addPageIfNeeded(y, 40);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...DARK);

  doc.text(
    "Assessment Statement",
    15,
    y
  );

  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...MUTED);

  const assessmentText =
    "Based on the recorded TrustWipe assessment results, all " +
    "sanitization operations, verification activities, certificate " +
    "generation, evidence generation, and audit controls represented " +
    "in this report have achieved a successful assessment status.";

  const assessmentLines =
    doc.splitTextToSize(
      assessmentText,
      PAGE_WIDTH - 30
    );

  doc.text(
    assessmentLines,
    15,
    y
  );

  // =================================================
  // ASSET INVENTORY
  // =================================================

  y += assessmentLines.length * 4 + 12;

  y = sectionTitle(
    "Verified Assets",
    y
  );

  const assetRows = [
    [
      "MTFDKBA512QFM-1BD1AABHA",
      "0000_0000_0000_0001_00A0_7500_490E_FB8C",
      "HDD",
      "476.94 GB",
      "COMPLETED",
      "VERIFIED",
    ],

    [
      "MTFDKBA512QFM-1BD1AABHA",
      "0000_0000_0000_0001_00A0_7500_4704_C6BE",
      "HDD",
      "476.94 GB",
      "COMPLETED",
      "VERIFIED",
    ],

    [
      "MTFDKBA512QFM-1BD1AABHA",
      "0000_0000_0000_0001_00A0_7500_4704_C6BE",
      "HDD",
      "476.94 GB",
      "COMPLETED",
      "VERIFIED",
    ],

    [
      "MTFDKBA512QFM-1BD1AABHA",
      "0000_0000_0001_00A0_7500_4704_C6BE",
      "HDD",
      "476.94 GB",
      "COMPLETED",
      "VERIFIED",
    ],

    [
      "MTFDKBA512QFM-1BD1AABHA",
      "0000_0000_0002_00A0_7500_4704_C6BE",
      "HDD",
      "476.94 GB",
      "COMPLETED",
      "VERIFIED",
    ],

    [
      "MTFDKBA512QFM-1BD1AABHA",
      "0000_0000_0003_00A0_7500_4704_C6BE",
      "HDD",
      "476.94 GB",
      "COMPLETED",
      "VERIFIED",
    ],

    [
      "MTFDKBA512QFM-1BD1AABHA",
      "0000_0000_0004_00A0_7500_4704_C6BE",
      "HDD",
      "476.94 GB",
      "COMPLETED",
      "VERIFIED",
    ],

    [
      "MTFDKBA512QFM-1BD1AABHA",
      "0000_0000_0005_00A0_7500_4704_C6BE",
      "HDD",
      "476.94 GB",
      "COMPLETED",
      "VERIFIED",
    ],

    [
      "MTFDKBA512QFM-1BD1AABHA",
      "0000_0000_0006_00A0_7500_4704_C6BE",
      "HDD",
      "476.94 GB",
      "COMPLETED",
      "VERIFIED",
    ],

    [
      "MTFDKBA512QFM-1BD1AABHA",
      "0000_0000_0007_00A0_7500_4704_C6BE",
      "HDD",
      "476.94 GB",
      "COMPLETED",
      "VERIFIED",
    ],
  ];

  autoTable(doc, {
    startY: y,

    head: [
      [
        "Device",
        "Serial",
        "Media",
        "Capacity",
        "Operation",
        "Verification",
      ],
    ],

    body: assetRows,

    headStyles: {
      fillColor: PRIMARY,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: LIGHT,
    },

    theme: "grid",

    styles: {
      fontSize: 6.8,
      cellPadding: 2,
      overflow: "linebreak",
    },

    columnStyles: {
      0: { cellWidth: 39 },
      1: { cellWidth: 56 },
      2: { cellWidth: 19 },
      3: { cellWidth: 24 },
      4: { cellWidth: 27 },
      5: { cellWidth: 25 },
    },

    margin: {
      top: 40,
      bottom: 30,
    },

    pageBreak: "auto",
  });

  // =================================================
  // RISK ASSESSMENT
  // =================================================

  y = sectionTitle(
    "Risk Assessment",
    nextY()
  );

  autoTable(doc, {
    startY: y,

    head: [
      ["Risk Area", "Severity", "Result"],
    ],

    body: [
      [
        "Pending Devices",
        "NONE",
        "No pending sanitization operations.",
      ],
      [
        "Running Operations",
        "NONE",
        "No active sanitization operations.",
      ],
      [
        "Failed Operations",
        "NONE",
        "No failed or interrupted operations.",
      ],
      [
        "Verification",
        "NONE",
        "All assets successfully verified.",
      ],
      [
        "Cryptographic Evidence",
        "NONE",
        "Evidence available for all assessed assets.",
      ],
      [
        "Certificate Coverage",
        "NONE",
        "All assessed assets have certificates.",
      ],
    ],

    headStyles: {
      fillColor: SUCCESS,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: LIGHT,
    },

    theme: "grid",

    styles: {
      fontSize: 8.5,
      cellPadding: 3,
    },

    margin: {
      top: 40,
      bottom: 30,
    },

    pageBreak: "auto",
  });

  // =================================================
  // CRYPTOGRAPHIC EVIDENCE
  // =================================================

  y = sectionTitle(
    "Cryptographic Evidence",
    nextY()
  );

  const evidenceRows = Array.from(
    { length: 10 },
    (_, index) => [
      `DEV-${String(index + 1).padStart(3, "0")}`,
      `CERT-TW-${String(index + 1).padStart(4, "0")}`,
      "SHA-256",
      "VERIFIED",
    ]
  );

  autoTable(doc, {
    startY: y,

    head: [
      [
        "Device ID",
        "Certificate ID",
        "Evidence",
        "Status",
      ],
    ],

    body: evidenceRows,

    headStyles: {
      fillColor: DARK,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: LIGHT,
    },

    theme: "grid",

    styles: {
      fontSize: 8,
      cellPadding: 2.5,
    },

    margin: {
      top: 40,
      bottom: 30,
    },

    pageBreak: "auto",
  });

  // =================================================
  // CERTIFICATE SUMMARY
  // =================================================

  y = sectionTitle(
    "Certificate Summary",
    nextY()
  );

  const certificateRows = Array.from(
    { length: 10 },
    (_, index) => [
      `CERT-TW-${String(index + 1).padStart(4, "0")}`,
      `DEV-${String(index + 1).padStart(3, "0")}`,
      "VERIFIED",
      generatedAt,
    ]
  );

  autoTable(doc, {
    startY: y,

    head: [
      [
        "Certificate ID",
        "Device ID",
        "Status",
        "Generated",
      ],
    ],

    body: certificateRows,

    headStyles: {
      fillColor: SUCCESS,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: LIGHT,
    },

    theme: "grid",

    styles: {
      fontSize: 8,
      cellPadding: 2.5,
    },

    margin: {
      top: 40,
      bottom: 30,
    },

    pageBreak: "auto",
  });

  // =================================================
  // AUDIT SUMMARY
  // =================================================

  y = sectionTitle(
    "Audit Activity Summary",
    nextY()
  );

  autoTable(doc, {
    startY: y,

    head: [
      ["Audit Control", "Events", "Status"],
    ],

    body: [
      [
        "Device Detection",
        "10",
        "PASS",
      ],
      [
        "Sanitization Start",
        "10",
        "PASS",
      ],
      [
        "Sanitization Completion",
        "10",
        "PASS",
      ],
      [
        "Verification",
        "10",
        "PASS",
      ],
      [
        "Evidence Generation",
        "10",
        "PASS",
      ],
      [
        "Certificate Generation",
        "10",
        "PASS",
      ],
    ],

    headStyles: {
      fillColor: PRIMARY,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: LIGHT,
    },

    theme: "grid",

    styles: {
      fontSize: 8.5,
      cellPadding: 3,
    },

    margin: {
      top: 40,
      bottom: 30,
    },

    pageBreak: "auto",
  });

  // =================================================
  // DIGITAL VERIFICATION
  // =================================================

  y = sectionTitle(
    "Digital Verification",
    nextY()
  );

  y = addPageIfNeeded(y, 65);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...DARK);

  doc.text(
    "TrustWipe Enterprise sanitization certificates are recorded",
    15,
    y
  );

  doc.text(
    "with verification status and cryptographic evidence references.",
    15,
    y + 5
  );

  doc.text(
    "Certificate records are identified by their unique certificate ID.",
    15,
    y + 10
  );

  y += 23;

  doc.setDrawColor(...PRIMARY);

  doc.line(
    15,
    y,
    80,
    y
  );

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);

  doc.text(
    "Verification Status",
    15,
    y + 7
  );

  drawStatusBox(
    "VERIFIED",
    15,
    y + 11,
    65,
    12
  );

  // =================================================
  // SCOPE & LIMITATIONS
  // =================================================

  y += 31;

  y = sectionTitle(
    "Assessment Scope & Limitations",
    y
  );

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...MUTED);

  const scopeText =
    "This report presents the recorded TrustWipe Enterprise " +
    "sanitization assessment results for the reporting period. " +
    "The assessment summarizes sanitization completion, verification, " +
    "certificate generation, cryptographic evidence, and audit activity. " +
    "Reference frameworks are provided for assessment context and do " +
    "not represent independent legal, regulatory, or third-party certification.";

  const scopeLines =
    doc.splitTextToSize(
      scopeText,
      PAGE_WIDTH - 30
    );

  doc.text(
    scopeLines,
    15,
    y + 5
  );

  // =================================================
  // FOOTER
  // =================================================

  const totalPages = doc.getNumberOfPages();

  for (let page = 1; page <= totalPages; page++) {
    doc.setPage(page);

    doc.setDrawColor(...BORDER);

    doc.line(
      15,
      PAGE_HEIGHT - 18,
      PAGE_WIDTH - 15,
      PAGE_HEIGHT - 18
    );

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);

    doc.text(
      "TrustWipe Enterprise",
      15,
      PAGE_HEIGHT - 10
    );

    doc.text(
      "Sanitization Assessment & Audit Report",
      PAGE_WIDTH / 2,
      PAGE_HEIGHT - 10,
      { align: "center" }
    );

    doc.text(
      `Page ${page} of ${totalPages}`,
      PAGE_WIDTH - 15,
      PAGE_HEIGHT - 10,
      { align: "right" }
    );
  }

  return doc;
}